/**
 * Populate DB with sample data on server start
 * to disable, edit config/environment/index.js, and set `seedDB: false`
 */
'use strict';
var theTable = {
  obj: require('./translator.model.js'),
  name: 'translators'
};

var theObjects = [
  {'name':'A. Duarte de Almeida'},
  {'name':'Abel Marques Ribeiro'},
  {'name':'Adelino dos Santos Rodrigues'},
  {'name':'Agostinho da Silva'},
  {'name':'Albano Martins'},
  {'name':'Alberto Gomes'},
  {'name':'Alexandre Pastor'},
  {'name':'Alexandre Pinheiro Torres'},
  {'name':'Alfredo Amorim'},
  {'name':'Alfredo Margarido'},
  {'name':'Álvaro de Almeida'},
  {'name':'Álvaro Gonçalves'},
  {'name':'Ana Patrão'},
  {'name':'Ana Saldanha'},
  {'name':'Anabela Carvalho Ferreira'},
  {'name':'Ângela Martha'},
  {'name':'António Barata'},
  {'name':'António M. Feijó'},
  {'name':'António Ramos Rosa'},
  {'name':'António Sérgio'},
  {'name':'António Vilalva'},
  {'name':'Aquilino Ribeiro'},
  {'name':'Armanda Rodrigues'},
  {'name':'Artur Guerra'},
  {'name':'Baptista de Carvalho'},
  {'name':'Bernardina Felgueiras'},
  {'name':'Cabral do Nascimento'},
  {'name':'Carlos Aboim de Brito'},
  {'name':'Carlos Afonso Lobo'},
  {'name':'Carlos Grifo'},
  {'name':'Carlos Santos'},
  {'name':'Casimiro Fernandes'},
  {'name':'Catherine Labey'},
  {'name':'Cecília Rego Pinheiro'},
  {'name':'Charles Baudelaire'},
  {'name':'Charles David Ley'},
  {'name':'Cristina Rodriguez'},
  {'name':'Daniel Gonçalves'},
  {'name':'E. Carrera Guerra'},
  {'name':'Egito Gonçalves'},
  {'name':'Eliane Zagury'},
  {'name':'Ernesto Rodrigues'},
  {'name':'Esmeralda Pereira'},
  {'name':'Eugénio de Andrade'},
  {'name':'Fátima Freire de Andrade'},
  {'name':'Fernanda Pinto Rodrigues'},
  {'name':'Fernando Guimarães'},
  {'name':'Filipe Guerra'},
  {'name':'Frederico Lourenço'},
  {'name':'G. Cascais Franco'},
  {'name':'Gabriela Alves Neves'},
  {'name':'Garibaldi Falcão'},
  {'name':'Geminiano Casais Franco'},
  {'name':'Gonçalo Gomes'},
  {'name':'Helena Domingos'},
  {'name':'Helena Pitta'},
  {'name':'Henrique Tavares e Castro'},
  {'name':'Henriques Tavares e Castro'},
  {'name':'Hygino Mendonça'},
  {'name':'Inês Duque Ribeiro'},
  {'name':'Ir. Maria Teresa de Paiva Nazareth'},
  {'name':'Isabel Alves'},
  {'name':'Isabel Cardoso'},
  {'name':'Isabel St. Aubyn'},
  {'name':'J. Freitas e Silva'},
  {'name':'J. Teixeira de Aguiar'},
  {'name':'Joana Varela'},
  {'name':'João Barrento'},
  {'name':'João Figueiredo Silva'},
  {'name':'João Gaspar Simões'},
  {'name':'João Lisboa'},
  {'name':'João Lourenço'},
  {'name':'João Palma-Ferreira'},
  {'name':'João Silva'},
  {'name':'Jorge Almeida e Pinho'},
  {'name':'Jorge Alves e Pedro Vilarinho'},
  {'name':'Jorge de Sena'},
  {'name':'Jorge Fallorca'},
  {'name':'Jorge Fazenda Lourenço'},
  {'name':'Jorge Reis'},
  {'name':'Jorge Telles de Menezes'},
  {'name':'José Agostinho Baptista'},
  {'name':'José Alberto Oliveira'},
  {'name':'José Alfredo Marques'},
  {'name':'José Bento'},
  {'name':'José Blanc de Portugal'},
  {'name':'José Correia Ribeiro'},
  {'name':'José de Freitas Cruz'},
  {'name':'José Lima'},
  {'name':'José Luis Luna'},
  {'name':'José Luís Luna'},
  {'name':'José M. Guardado Moreira'},
  {'name':'José Marinho'},
  {'name':'José Miguel Silva'},
  {'name':'José Palla e Carmo'},
  {'name':'José Rodrigues Miguéis'},
  {'name':'José Vieira de Lima'},
  {'name':'Júlio Henriques'},
  {'name':'Liane de Oliveira'},
  {'name':'Lígia Junqueira Smith'},
  {'name':'Lino Vallandro'},
  {'name':'Luís Nazaré'},
  {'name':'Luís Silveira'},
  {'name':'Luísa Neto Jorge'},
  {'name':'Lumir Nahodil'},
  {'name':'M. Villaverde Cabral'},
  {'name':'Manuel João Gomes'},
  {'name':'Manuel Marques'},
  {'name':'Manuel Portela'},
  {'name':'Manuela de Sousa Marques'},
  {'name':'Manuela Porto'},
  {'name':'Margarida Vale de Gato'},
  {'name':'Maria Adélia Silva Melo'},
  {'name':'Maria Alexandra A. Lopes'},
  {'name':'Maria Antunes'},
  {'name':'Maria da Conceição Janeiro'},
  {'name':'Maria da Graça Cardoso'},
  {'name':'Maria da Piedade Ferreira'},
  {'name':'Maria do Carmo Cary'},
  {'name':'Maria do Carmo Romão'},
  {'name':'Maria Dulce Teles de Menezes'},
  {'name':'Maria Emília Marques Mano'},
  {'name':'Maria Filomena Duarte'},
  {'name':'Maria Franco'},
  {'name':'Maria Isabel Gonçalves Tomás'},
  {'name':'Maria João Freire de Andrade'},
  {'name':'Maria Jorge Vilar de Figueiredo'},
  {'name':'Maria José Palla'},
  {'name':'Maria Lúcia Teles de Menezes'},
  {'name':'Maria Manuela Ribeiro Costa'},
  {'name':'Maria Mello'},
  {'name':'Maria Odete Gonçalves-Koller'},
  {'name':'Maria Ondina'},
  {'name':'Maria Teresa Belo'},
  {'name':'Maria Tereza de Barros Brito'},
  {'name':'Marina Santos'},
  {'name':'Mário Avelar'},
  {'name':'Mário Cesariny'},
  {'name':'Mário Henrique Leiria'},
  {'name':'Mário Quintana'},
  {'name':'Mercedes Balsemão'},
  {'name':'Miguel Cardoso'},
  {'name':'Monica Cozacenco'},
  {'name':'Monica Cozaceno'},
  {'name':'Napoleão Toscano'},
  {'name':'Nina Guerra '},
  {'name':'Nuno Fernandes'},
  {'name':'Olga Gonçalves'},
  {'name':'Óscar de Freitas Lopes'},
  {'name':'P. J. de Morais'},
  {'name':'Paula Amaral'},
  {'name':'Paula Caetano'},
  {'name':'Paulo Faria'},
  {'name':'Paulo Quintela'},
  {'name':'Paulo Santa-Rita'},
  {'name':'Pedro Baptista'},
  {'name':'Pedro Guilherme dos Santos Diniz'},
  {'name':'Pedro Silva'},
  {'name':'Pedro Tamen'},
  {'name':'Pedro Vidal'},
  {'name':'Pedro Vidoeira'},
  {'name':'Pilar Delvaux'},
  {'name':'Raquel Mota'},
  {'name':'Ricardo Pereira'},
  {'name':'Richard Zenith'},
  {'name':'Rita Assis Santos'},
  {'name':'S. Pinto'},
  {'name':'Salvador Guerra'},
  {'name':'Sofia Gomes'},
  {'name':'Sónia Oliveira'},
  {'name':'Susana Pires'},
  {'name':'Teresa Aica Bairos'},
  {'name':'Teresa Aica Barros'},
  {'name':'Teresa Casal'},
  {'name':'Tipografia Poliglota Vaticana'},
  {'name':'Urbano Tavares Rodrigues'},
  {'name':'Vários'},
  {'name':'Vera San Payo de Lemos'},
  {'name':'Vidal de Oliveira'},
  {'name':'Vidal Oliveira'},
  {'name':'Virgínia Mota'},
  {'name':'Vitorino Magalhães Godinho'},
  {'name':'Xavier da Cunha'},
  {'name':'Fernando Pessoa'},
  {'name':'João Félix Galizes'},
  {'name':'Nina Guerra e Filipe Guerra'},
  {'name':' João Gaspar Simões'},
  {'name':'Nina Guerra'},
  {'name':' Inês Duque Ribeiro'},
  {'name':' M. Villaverde Cabral'},
  {'name':' Maria Teresa Belo'},
  {'name':' Margarida Vale de Gato'},
  {'name':' Filipe Guerra'},
  {'name':' E. Carrera Guerra'},
  {'name':'Maria Frnco'},
  {'name':' Carlos Afonso Lobo'},
  {'name':' Daniel Gonçalves'},
  {'name':'Nina Guerra'},
  {'name':' Luísa Neto Jorge'},
  {'name':' Maria Mello'},
  {'name':' Cabral do Nascimento'},
  {'name':'Tradução de Manuel João Gomes'},
  {'name':' Artur Guerra'},
  {'name':' Filipe Guerra'},
  {'name':' João Lourenço'},
  {'name':'Rui Viana Pereira'},
  {'name':'Cristina Maria Ovídio Baptista'},
  {'name':'Thierry Sandaldjian'},

];

require('../tables/tables.seed')(theTable, theObjects);
