/**
 * Populate DB with sample data on server start
 * to disable, edit config/environment/index.js, and set `seedDB: false`
 */

'use strict';
var Book = require('./bookconfig.model');
console.log('seeding book config...');
Book.find({}).remove(function () {
  Book.create(
    {
      search: {
        limitDefault: 50,
        limitFeatured: 8
      },
      placeholders: {
        reference: 'referência',
        title: 'título do livro',
        authors: 'autor ou autores do livro',
        subject: 'assunto',
        editionNumber: 'nº edição',
        editionYear: '1500-actual',
        editionLanguage: 'idioma',
        editionCountry: 'país',
        editionPublisher: 'editora',
        editionTranslatedLanguage: 'Traduzido do',
        editionCountryFirstPublisher: 'Editora da 1ª edição',
        editionYearCountryFirstEdition: 'Ano da 1ª edição',
        editionISBN: 'ISBN',
        originalLanguage: 'Idioma',
        originalTitle: 'Título',
        originalPublisher: 'Editora',
        originalYearFirstEdition: 'Ano',
        originalCountryEdition: 'País',
        nameCollection: 'Colecção',
        numCollection: 'Nº na colecção',
        translators: 'Tradução por',
        prefaceBy: 'Prefácio de',
        postfaceBy: 'Posfácio de',
        graphicalPrint: 'Impressão Gráfica',
        cover: 'Capa',
        images: 'Imagens',
        workmanship: 'Acabamento',
        pagesNum: 'NºPág',
        priceInitial: 'Preço Inicial',
        priceCost: 'Preço de Custo',
        price: 'Preço',
        buyAt: 'Local de Compra',
        editionLegalDeposit: 'Depósito Legal',
        circulation: 'Tiragem',
        keywords: 'Palavras-Chave',
        archive: 'Localização Arquivo',
        condition: 'Condição',
        lendingTo: 'Empréstimo',
        obs: 'Observações (internet)',
        obsInternal: 'Observações',
        correctors: 'Correctores',
        subtitle: 'Sub-Título',
        dimensions: 'Dimensões',
        weight: 'Peso',
        numVolume: 'NºVol',
        qt: 'Quantidade',
        categories: 'Categorias',
        template: 'Template',
        dateResgistration: 'Data de Registo',
        dateUpdate: 'Data de Modificação'
      },
      labels: {
        reference: 'Nº / Refª',
        title: 'Título',
        authors: 'Autor',
        subject: 'Assunto',
        editionNumber: 'Nº edição',
        editionYear: 'Ano',
        editionLanguage: 'Idioma',
        editionCountry: 'País',
        editionPublisher: 'Editora',
        editionTranslatedLanguage: 'Traduzido do',
        editionCountryFirstPublisher: 'Editora 1ª edição',
        editionYearCountryFirstEdition: 'Ano 1ª edição',
        editionISBN: 'ISBN',
        originalLanguage: 'Idioma',
        originalTitle: 'Título',
        originalPublisher: 'Editora',
        originalYearFirstEdition: 'Ano',
        originalCountryEdition: 'País',
        nameCollection: 'Colecção',
        numCollection: 'Nº',
        translators: 'Tradução por',
        prefaceBy: 'Prefácio de',
        postfaceBy: 'Posfácio de',
        graphicalPrint: 'Impressão Gráfica',
        cover: 'Capa',
        images: 'Imagens',
        workmanship: 'Acabamento',
        pagesNum: 'NºPág',
        priceInitial: 'Preço Inicial',
        priceCost: 'Preço de Custo',
        price: 'Preço',
        buyAt: 'Local de Compra',
        editionLegalDeposit: 'Depósito Legal',
        circulation: 'Tiragem',
        keywords: 'Palavras-Chave',
        archive: 'Localização Arquivo',
        condition: 'Condição',
        lendingTo: 'Empréstimo',
        obs: 'Observações (internet)',
        obsInternal: 'Observações',
        correctors: 'Correctores',
        subtitle: 'Sub-Título',
        dimensions: 'Dimensões',
        weight: 'Peso',
        numVolume: 'NºVol',
        qt: 'Qt.',
        categories: 'Categorias',
        isNewBook: 'É novo',
        isFeatured: 'Em destaque',
        isPromotion: 'Em promoção',
        isRare: 'É raro',
        isUnique: 'É único',
        isValuable: 'É valioso',
        sellOnline: 'Venda na internet',
        sellPresencial: 'Venda em mão',
        qtStore: 'Qt. em loja',
        qtSold: 'Qt. vendida',
        discounts: 'Desconto',
        taxes: 'Taxa',
        template: 'Template',
        dateResgistration: 'Data de Registo',
        dateUpdate: 'Data de Modificação'
      },
      valMessages: {
        'title': {'required': 'o título é obrigatório'},
        'editionYear': {'invalid': 'ano entre 1500-Ano actual'},
        'originalYearFirstEdition': {'invalid': 'ano entre 1500-Ano actual'},
        'editionNumber': {'invalid': 'valor inválido'},
        'circulation': {'invalid': 'valor inválido'},
        'editionISBN': {'invalid': 'ISBN inválido'},
        'price': {'invalid': 'valor inválido'},
        'priceInitial': {'invalid': 'valor inválido'},
        'priceCost': {'invalid': 'valor inválido'},
        'qt': {'invalid': 'valor inválido'},
        'qtSold': {'invalid': 'valor inválido'},
        'qtStore': {'invalid': 'valor inválido'}
      }

    }
  );
});
