/**
 * Populate DB with sample data on server start
 * to disable, edit config/environment/index.js, and set `seedDB: false`
 */

'use strict';
var Category = require('./category.model');

count( function(err, num) {
  if ( err ) {return;}
  if (num === 0) {
    console.log('seeding categories...');

    seed(function(err) {
      if ( err ) {return;}
      count(function(err, num) {
        if ( err ) {return;}
        console.log('categories seeded: ', num);
      });
    });
  }
  console.log('categories: ', num);
});

function count(callback) {
  Category.count({}, function( err, count ) {
    callback(err, count);
  });
}

function seed(callback) {
  Category.create(
    {'name': 'Administração Pública'},
    {'name': 'África'},
    {'name': 'Agricultura E Pecuária'},
    {'name': 'Almanaques'},
    {'name': 'Antiguidades'},
    {'name': 'Antoniana'},
    {'name': 'Antropologia'},
    {'name': 'Armaria'},
    {'name': 'Arqueologia'},
    {'name': 'Arquitectura'},
    {'name': 'Arte'},
    {'name': 'Associativismo E Corporativismo'},
    {'name': 'Astrologia'},
    {'name': 'Astronáutica'},
    {'name': 'Astronomia'},
    {'name': 'Auto-Ajuda'},
    {'name': 'Automóveis'},
    {'name': 'Aviação'},
    {'name': 'Banda Desenhada'},
    {'name': 'Bibliografia'},
    {'name': 'Biografia E Iconografia'},
    {'name': 'Biografias'},
    {'name': 'Biologia'},
    {'name': 'Botânica'},
    {'name': 'Caça'},
    {'name': 'Caça E Pesca'},
    {'name': 'Caligrafia E Paleografia'},
    {'name': 'Caminhos De Ferro'},
    {'name': 'Cartonismo'},
    {'name': 'Casa Real'},
    {'name': 'Ciência'},
    {'name': 'Ciências Da Natureza'},
    {'name': 'Cinema'},
    {'name': 'Climatologia'},
    {'name': 'Coleccionismo'},
    {'name': 'Colonialismo'},
    {'name': 'Colonização'},
    {'name': 'Comboios'},
    {'name': 'Comunicações'},
    {'name': 'Constituições'},
    {'name': 'Contabilidade E Comércio'},
    {'name': 'Corografia'},
    {'name': 'Culinária'},
    {'name': 'Culinária & Gastronomia'},
    {'name': 'Cultura'},
    {'name': 'Dança'},
    {'name': 'Descobrimentos'},
    {'name': 'Descobrimentos E Cartografia'},
    {'name': 'Desenho'},
    {'name': 'Design'},
    {'name': 'Desporto'},
    {'name': 'Desporto E Jogos'},
    {'name': 'Dicionários'},
    {'name': 'Diplomacia'},
    {'name': 'Diplomática'},
    {'name': 'Direito'},
    {'name': 'Dissertações'},
    {'name': 'Documentação'},
    {'name': 'Economia'},
    {'name': 'Economia E Finanças'},
    {'name': 'Edições De Luxo'},
    {'name': 'Edições Especiais E Numeradas'},
    {'name': 'Edições Ilustradas'},
    {'name': 'Educação E Ensino'},
    {'name': 'Emblemática'},
    {'name': 'Encadernação (Técnicas De)'},
    {'name': 'Encadernações'},
    {'name': 'Encadernações Artísticas E Armoriadas'},
    {'name': 'Engenharia'},
    {'name': 'Enologia E Viticultura'},
    {'name': 'Ensaio'},
    {'name': 'Epistolografia'},
    {'name': 'Equitação'},
    {'name': 'Erótica'},
    {'name': 'Escravatura'},
    {'name': 'Estado Novo'},
    {'name': 'Etnografia'},
    {'name': 'Ex-Libris'},
    {'name': 'Exposições'},
    {'name': 'Fac-Similes'},
    {'name': 'Filologia E Ortografia'},
    {'name': 'Filosofia'},
    {'name': 'Fotografia'},
    {'name': 'Fotografia E Cinema'},
    {'name': 'Genealogia'},
    {'name': 'Geografia'},
    {'name': 'Gramática'},
    {'name': 'Grandes Guerras'},
    {'name': 'Gravura E Desenho'},
    {'name': 'Gregos-Latinos'},
    {'name': 'Guerra'},
    {'name': 'Guerra Peninsular'},
    {'name': 'Hagiografia'},
    {'name': 'Henriquina'},
    {'name': 'Heráldica E Nobiliarquia'},
    {'name': 'Hidráulica'},
    {'name': 'Hidrografia'},
    {'name': 'Hidrologia E Termalismo'},
    {'name': 'Higiene & Saúde'},
    {'name': 'Hipologia'},
    {'name': 'História'},
    {'name': 'História Natural'},
    {'name': 'Hotelaria E Restauração'},
    {'name': 'Humanismo'},
    {'name': 'Humorismo'},
    {'name': 'Iluminura'},
    {'name': 'Imprensa E Jornalismo'},
    {'name': 'Impressionismo'},
    {'name': 'Indústria'},
    {'name': 'In-Memoriam'},
    {'name': 'Inquisição'},
    {'name': 'Jesuítica'},
    {'name': 'Jornais'},
    {'name': 'Judaica'},
    {'name': 'Linguística'},
    {'name': 'Literatura'},
    {'name': 'Literatura Alemã'},
    {'name': 'Literatura Americana'},
    {'name': 'Literatura Brasileira'},
    {'name': 'Literatura Clássica'},
    {'name': 'Literatura Espanhola'},
    {'name': 'Literatura Estrangeira'},
    {'name': 'Literatura Infantil'},
    {'name': 'Literatura Latino Americana'},
    {'name': 'Literatura Portuguesa'},
    {'name': 'Literatura Russa'},
    {'name': 'Literatura Soviética'},
    {'name': 'Literatura Universal'},
    {'name': 'Livros Do Séc XVII'},
    {'name': 'Livros Do Séc XVIII'},
    {'name': 'Livros Quinhentistas'},
    {'name': 'Maçonaria'},
    {'name': 'Magia E Ilusionismo'},
    {'name': 'Manuscritos'},
    {'name': 'Mapas'},
    {'name': 'Marinha'},
    {'name': 'Matemáticas'},
    {'name': 'Medicina'},
    {'name': 'Medicina E Farmácia'},
    {'name': 'Medicina Natural'},
    {'name': 'Memórias'},
    {'name': 'Memórias E Autobiografias'},
    {'name': 'Meteorologia'},
    {'name': 'Militária'},
    {'name': 'Misericórdias'},
    {'name': 'Mitologia'},
    {'name': 'Monarquia'},
    {'name': 'Monografias Gerais'},
    {'name': 'Monografias Locais'},
    {'name': 'Monografias Regionais'},
    {'name': 'Moral'},
    {'name': 'Museologia'},
    {'name': 'Música'},
    {'name': 'Música E Dança'},
    {'name': 'Napoleónica'},
    {'name': 'Numismática E Medalhística'},
    {'name': 'Objectos De Museu'},
    {'name': 'Obras Por Classificar'},
    {'name': 'Obras Públicas'},
    {'name': 'Ocultismo E Espiritismo'},
    {'name': 'Ordens Honoríficas'},
    {'name': 'Ordens Militares'},
    {'name': 'Ordens Religiosas'},
    {'name': 'Países'},
    {'name': 'Pedagogia'},
    {'name': 'Periódicos'},
    {'name': 'Pesos E Medidas'},
    {'name': 'Pintura'},
    {'name': 'Poesia'},
    {'name': 'Poesia Angolana'},
    {'name': 'Poesia Brasileira'},
    {'name': 'Poesia Espanhola'},
    {'name': 'Poesia Portuguesa'},
    {'name': 'Policial'},
    {'name': 'Política'},
    {'name': 'Primeiras Edições'},
    {'name': 'Propaganda Politica'},
    {'name': 'Psicanálise'},
    {'name': 'Psicologia'},
    {'name': 'Psiquiatria'},
    {'name': 'Publicações Periódicas'},
    {'name': 'Publicidade'},
    {'name': 'Religião'},
    {'name': 'Renascimento'},
    {'name': 'Revistas'},
    {'name': 'Revoluções'},
    {'name': 'Romance'},
    {'name': 'Romance Impressionista'},
    {'name': 'Sebástica'},
    {'name': 'Seguros'},
    {'name': 'Sexualidade'},
    {'name': 'Simbologia E Numerologia'},
    {'name': 'Sociologia'},
    {'name': 'Tauromaquia'},
    {'name': 'Teatro'},
    {'name': 'Técnicas'},
    {'name': 'Tese'},
    {'name': 'Tipografia'},
    {'name': 'Trajo E Costumes'},
    {'name': 'Transportes'},
    {'name': 'Turismo'},
    {'name': 'Urbanismo'},
    {'name': 'Vária'},
    {'name': 'Veterinária'},
    {'name': 'Viagens'},
    {'name': 'Vinho'},
    {'name': 'Zoologia'},
    callback
  );
}
