/**
 * Populate DB with sample data on server start
 * to disable, edit config/environment/index.js, and set `seedDB: false`
 */

'use strict';
var Category = require('./category.model');
console.log('seeding categories...');
Category.find({}).remove(function () {
  Category.create(
    {"name": "África"},
    {"name": "Administração Pública"},
    {"name": "Agricultura E Pecuária"},
    {"name": "Almanaques"},
    {"name": "Antiguidades"},
    {"name": "Antoniana"},
    {"name": "Antropologia"},
    {"name": "Antropologia"},
    {"name": "Armaria"},
    {"name": "Armaria"},
    {"name": "Arqueologia"},
    {"name": "Arqueologia"},
    {"name": "Arquitectura"},
    {"name": "Arquitectura"},
    {"name": "Arte"},
    {"name": "Arte"},
    {"name": "Associativismo E Corporativismo"},
    {"name": "Astrologia"},
    {"name": "Astronáutica"},
    {"name": "Astronomia"},
    {"name": "Automóveis"},
    {"name": "Aviação"},
    {"name": "Banda Desenhada"},
    {"name": "Bibliografia"},
    {"name": "Biografia E Iconografia"},
    {"name": "Biografias"},
    {"name": "Biologia"},
    {"name": "Botânica"},
    {"name": "Caça"},
    {"name": "Caça E Pesca"},
    {"name": "Caligrafia E Paleografia"},
    {"name": "Caminhos De Ferro"},
    {"name": "Casa Real"},
    {"name": "Ciência"},
    {"name": "Ciências Da Natureza"},
    {"name": "Cinema"},
    {"name": "Climatologia"},
    {"name": "Coleccionismo"},
    {"name": "Colonialismo"},
    {"name": "Colonização"},
    {"name": "Comboios"},
    {"name": "Comunicações"},
    {"name": "Constituições"},
    {"name": "Contabilidade E Comércio"},
    {"name": "Corografia"},
    {"name": "Culinária"},
    {"name": "Culinária & Gastronomia"},
    {"name": "Cultura"},
    {"name": "Dança"},
    {"name": "Descobrimentos"},
    {"name": "Descobrimentos E Cartografia"},
    {"name": "Design"},
    {"name": "Desporto"},
    {"name": "Desporto E Jogos"},
    {"name": "Dicionários"},
    {"name": "Diplomática"},
    {"name": "Diplomacia"},
    {"name": "Direito"},
    {"name": "Dissertações"},
    {"name": "Documentação"},
    {"name": "Economia"},
    {"name": "Economia E Finanças"},
    {"name": "Edições De Luxo"},
    {"name": "Edições Especiais E Numeradas"},
    {"name": "Edições Ilustradas"},
    {"name": "Educação E Ensino"},
    {"name": "Emblemática"},
    {"name": "Encadernação (Técnicas De)"},
    {"name": "Encadernações"},
    {"name": "Encadernações Artísticas E Armoriadas"},
    {"name": "Engenharia"},
    {"name": "Enologia E Viticultura"},
    {"name": "Ensaio"},
    {"name": "Epistolografia"},
    {"name": "Equitação"},
    {"name": "Erótica"},
    {"name": "Escravatura"},
    {"name": "Estado Novo"},
    {"name": "Etnografia"},
    {"name": "Ex-Libris"},
    {"name": "Exposições"},
    {"name": "Fac-Similes"},
    {"name": "Filologia E Ortografia"},
    {"name": "Filosofia"},
    {"name": "Fotografia"},
    {"name": "Fotografia E Cinema"},
    {"name": "Genealogia"},
    {"name": "Geografia"},
    {"name": "Gramática"},
    {"name": "Grandes Guerras"},
    {"name": "Gravura E Desenho"},
    {"name": "Gregos-Latinos"},
    {"name": "Guerra"},
    {"name": "Guerra Peninsular"},
    {"name": "Hagiografia"},
    {"name": "Henriquina"},
    {"name": "Heráldica E Nobiliarquia"},
    {"name": "Hidráulica"},
    {"name": "Hidrografia"},
    {"name": "Hidrologia E Termalismo"},
    {"name": "Higiene & Saúde"},
    {"name": "Hipologia"},
    {"name": "História"},
    {"name": "História"},
    {"name": "História Natural"},
    {"name": "Hotelaria E Restauração"},
    {"name": "Humanismo"},
    {"name": "Humorismo"},
    {"name": "Iluminura"},
    {"name": "Imprensa E Jornalismo"},
    {"name": "In-Memoriam"},
    {"name": "Indústria"},
    {"name": "Inquisição"},
    {"name": "Jesuítica"},
    {"name": "Jornais"},
    {"name": "Judaica"},
    {"name": "Linguística"},
    {"name": "Literatura"},
    {"name": "Literatura Clássica"},
    {"name": "Literatura Estrangeira"},
    {"name": "Literatura Infantil"},
    {"name": "Literatura Portuguesa"},
    {"name": "Livros Do Séc Xvii"},
    {"name": "Livros Do Séc Xviii"},
    {"name": "Livros Quinhentistas"},
    {"name": "Literatura Universal"},
    {"name": "Música"},
    {"name": "Música E Dança"},
    {"name": "Maçonaria"},
    {"name": "Maçonaria"},
    {"name": "Magia E Ilusionismo"},
    {"name": "Manuscritos"},
    {"name": "Manuscritos"},
    {"name": "Mapas"},
    {"name": "Marinha"},
    {"name": "Matemáticas"},
    {"name": "Medicina"},
    {"name": "Medicina E Farmácia"},
    {"name": "Medicina Natural"},
    {"name": "Memórias"},
    {"name": "Memórias E Autobiografias"},
    {"name": "Meteorologia"},
    {"name": "Militária"},
    {"name": "Misericórdias"},
    {"name": "Mitologia"},
    {"name": "Monarquia"},
    {"name": "Monarquia"},
    {"name": "Monografias Gerais"},
    {"name": "Monografias Locais"},
    {"name": "Monografias Regionais"},
    {"name": "Moral"},
    {"name": "Museologia"},
    {"name": "Napoleónica"},
    {"name": "Numismática E Medalhística"},
    {"name": "Objectos De Museu"},
    {"name": "Obras Públicas"},
    {"name": "Obras Por Classificar"},
    {"name": "Ocultismo E Espiritismo"},
    {"name": "Ordens Honoríficas"},
    {"name": "Ordens Militares"},
    {"name": "Ordens Religiosas"},
    {"name": "Países"},
    {"name": "Pedagogia"},
    {"name": "Periódicos"},
    {"name": "Pesos E Medidas"},
    {"name": "Poesia"},
    {"name": "Política"},
    {"name": "Primeiras Edições"},
    {"name": "Propaganda Politica"},
    {"name": "Psicanálise"},
    {"name": "Psicologia"},
    {"name": "Psiquiatria"},
    {"name": "Publicações Periódicas"},
    {"name": "Publicidade"},
    {"name": "Religião"},
    {"name": "Renascimento"},
    {"name": "Revistas"},
    {"name": "Revoluções"},
    {"name": "Sebástica"},
    {"name": "Seguros"},
    {"name": "Sexualidade"},
    {"name": "Simbologia E Numerologia"},
    {"name": "Sociologia"},
    {"name": "Técnicas"},
    {"name": "Tauromaquia"},
    {"name": "Teatro"},
    {"name": "Tese"},
    {"name": "Tipografia"},
    {"name": "Trajo E Costumes"},
    {"name": "Transportes"},
    {"name": "Turismo"},
    {"name": "Urbanismo"},
    {"name": "Vária"},
    {"name": "Veterinária"},
    {"name": "Viagens"},
    {"name": "Vinho"},
    {"name": "Zoologia"}
  );
});
